version: '3'
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=production
    depends_on:
      - db
  db:
    image: nouchka/sqlite3
    volumes:
      - database_data:/data
volumes:
  database_data: